function Schema = get_schema()
    % Returns USAIN input fields schema

    IA = InputAttributes;

    fields = [ ...
        validate.Field('ADDITIONAL_SCF_FLS', ...
            default = 1.0, ...
            expected = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('ADDITIONAL_SCF_ULS', ...
            default = 1.0, ...
            expected = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('ALW_LOWER_FLANGE_THICKNESS', ...
            default = 2, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('ALW_UPPER_FLANGE_THICKNESS', ...
            default = 2, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('B_MIN', ...
             default = nan, ...
             units = Unit.mm, ...
             min_ = 10, ...
             max_ = 250, ...
             classes = IA.CLS_NUM, ...
             attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('BEVEL_ANGLE', ...
            default = 42, ...
            units =  Unit.deg, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('BEVEL_ROOT_FACE', ...
            default = 4, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('BOLT_DIAMETER_SELECTION', ...
            default = 'all', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            valFunc = IA.make_list_valfun('BOLT_DIAMETER_SELECTION', ["all", "uls"]))

        validate.Field('BoltFls.BOLT_FORCE_MODEL', ...
            default = 'schmidtneuper', ...
            valFunc = IA.make_list_valfun('BoltFls.BOLT_FORCE_MODEL', UsainUtils.BoltForceModelFactory.OPTIONS), ...
            repeat = true)

        validate.Field('BoltFls.CUSTOM_PRELOAD', ...
            default = nan, ...
            units = Unit.kN, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('BoltFls.PRELOAD_LOSS_FACTOR_FLS', ...
            default = 0.9, ...
            min_ = 0.7, ...
            max_ = 0.9, ...
            classes = IA.CLS_NUM, ...
            attributes = [IA.ATTR_NUM_SCNONNEG, '<=', 1], ...
            repeat = true)

        validate.Field('BoltFls.PSF_BOLT_MATERIAL_FLS', ...
            default = nan, ...
            min_ = 0.9, ...
            max_ = 2, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG, ...
            repeat = true)

        validate.Field('BoltFls.SN_CURVE_BOLT', ...
            default = '', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            repeat = true)

        validate.Field('BoltFls.TARGET_PM_SUM', ...
            default = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG, ...
            repeat = true)

        validate.Field('BoltFls.THICKNESS_EXPONENT_BOLT', ...
            default = nan, ...
            classes = IA.CLS_NUM, ...
            attributes = [IA.ATTR_NUM_SCNONNEG, '<', 1], ...
            repeat = true)

        validate.Field('boltOptions', ...
            valFunc = {@(x, ~) usain.fastener.GarnitureData.validate_bolt_options(x)})

        validate.Field('CLEARANCE_FILLET_WELD', ...
            default = 20, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('countryCode', ...
            default = 'ROW', ...
            valFunc = IA.make_list_valfun('countryCode', USAIN.VALID_COUNTRY_CODES))

        validate.Field('CUSTOM_WASHER_DIAM_INNER', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 40, ...
            max_ = 200, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('CUSTOM_WASHER_DIAM_OUTER', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 40, ...
            max_ = 200, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('CUSTOM_WASHER_THICKNESS', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 6, ...
            max_ = 25, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('DEAD_WEIGHT', ...
            default = nan, ...
            units = Unit.kN, ...
            min_ = 0, ...
            max_ = 1e5, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('DEL_WOHLER_SLOPE', ...
            default = 4, ...
            min_ = 3.5, ...
            max_ = 4, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('DEL_REF_CYCLES', ...
            default = 1e7, ...
            expected = 1e7, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('diamBoltCircle', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 2500, ...
            max_ = 9000, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('diamBoltHole', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 40, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('diameter', ...
             default = nan, ...
             units = Unit.mm, ...
             min_ = 2500, ...
             max_ = 10000, ...
             classes = IA.CLS_NUM, ...
             attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('diameterReference', ...
            default = 'outneck', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            valFunc = IA.make_list_valfun('diameterReference', ["outneck", "outermost"]))

         validate.Field('DO_ALLOW_SWITCH_L_TO_T', ...
            default = false, ...
            valFunc = {IA.make_bool_valfun('DO_ALLOW_SWITCH_L_TO_T')})

        validate.Field('DO_ASSESS_BOLT_PLASTICITY', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_BOLT_PLASTICITY')})

        validate.Field('DO_ASSESS_BOLT_THREAD_REQ', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_BOLT_THREAD_REQ')})

        validate.Field('DO_ASSESS_FLANGE_NECK_SCF', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_FLANGE_NECK_SCF')})

        validate.Field('DO_ASSESS_FLANGE_PLASTICITY', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_FLANGE_PLASTICITY')})

        validate.Field('DO_ASSESS_FLS', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_FLS')})

        validate.Field('DO_ASSESS_GAPPING', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_GAPPING')})

        validate.Field('DO_ASSESS_SCHMIDTNEUPER_APT', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_SCHMIDTNEUPER_APT')})

        validate.Field('DO_ASSESS_SLS_PRETENSION', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_SLS_PRETENSION')})

        validate.Field('DO_ASSESS_ULS', ...
            default = nan, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_ULS')})

        validate.Field('DO_ASSESS_ULS_JPN', ...
            default = nan, ...
            valFunc = {IA.make_bool_valfun('DO_ASSESS_ULS_JPN')})

        validate.Field('DO_SAVE_FULL_FILE', ...
            default = false, ...
            valFunc = {IA.make_bool_valfun('DO_SAVE_FULL_FILE')})

        validate.Field('DO_TRIM_DESIGN_SPACE', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_TRIM_DESIGN_SPACE')})

         validate.Field('DO_UPDATE_DESIGN_SPACE', ...
            default = true, ...
            expected = true, ...
            valFunc = {IA.make_bool_valfun('DO_UPDATE_DESIGN_SPACE')})

        validate.Field('DOOR_SEGMENT.DO_INCLUDE', ...
            default = false, ...
            valFunc = {IA.make_bool_valfun('DOOR_SEGMENT.DO_INCLUDE')})

        validate.Field('DOOR_SEGMENT.FACTOR_CAN_TO_DOOR_THICKNESS', ...
            default = 1.3, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('DOOR_SEGMENT.MIN_CAN_TO_DOOR_DELTA_THICKNESS', ...
            default = 20, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('DOOR_SEGMENT.THICKNESS', ...
            default = nan, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('E_BOLT', ...
            default = nan, ...
            min_ = 200, ...
            max_ = 220, ...
            units =  Unit.GPa, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('E_FLANGE', ...
            default = nan, ...
            min_ = 200, ...
            max_ = 220, ...
            units =  Unit.GPa, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('FDI_COEFFICIENT_A1', ...
            default = 0.1, ...
            min_ = 0.01, ...
            max_ = 1, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('FDI_COEFFICIENT_A2', ...
            default = 0.0003, ...
            min_ = 0.0001, ...
            max_ = 0.001, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('FlangeGapping.CUSTOM_PRELOAD', ...
            default = nan, ...
            units = Unit.kN, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('FlangeNeckScf.CUSTOM_PRELOAD', ...
            default = nan, ...
            units = Unit.kN, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('FlangeNeckScf.PRELOAD_LOSS_FACTOR_FLS', ...
            default = 0.9, ...
            min_ = 0.7, ...
            max_ = 0.9, ...
            classes = IA.CLS_NUM, ...
            attributes = [IA.ATTR_NUM_SCNONNEG, '<=', 1])

        validate.Field('FlangeNeckScf.TARGET_PM_SUM', ...
            default = 1.0, ...
            expected = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('FlangeNeckScf.WRITE_INTERMEDIATE_RESULTS', ...
            default = false, ...
            valFunc = {IA.make_bool_valfun('FlangeNeckScf.WRITE_INTERMEDIATE_RESULTS')})

        validate.Field('FLANGE_STEEL_TYPE', ...
            default = '', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR)

        validate.Field('flangeType', ...
            default = '', ...
            valFunc = IA.make_list_valfun('flangeType', UsainUtils.FlangeModel.VALID_FLANGE_TYPES))

        validate.Field('FILLET_RADIUS', ...
            default = 10, ...
            min_ = 10, ...
            max_ = 50, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('GLOBAL_MAX_BOLT_DISTANCE', ...
            default = nan, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('GLOBAL_MIN_BOLT_DISTANCE', ...
            default = nan, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('heightNoseLo', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 25, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('heightNoseUp', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 25, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('IGNORE_BOLT_EXTENDER', ...
            default = true, ...
            valFunc = {IA.make_bool_valfun('IGNORE_BOLT_EXTENDER')})

        validate.Field('INCLINATION_MOMENT', ...
            default = nan, ...
            units = Unit.kNm, ...
            min_ = 0, ...
            max_ = 1e5, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('INCLINATION_MOMENT_FLS', ...
            default = nan, ...
            units = Unit.kNm, ...
            min_ = 0, ...
            max_ = 1e5, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('lengthBoltExtender', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 0, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECNONNEG)

        validate.Field('Loads.dlcFilter', ...
            default = '.*', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            repeat = true)

        validate.Field('Loads.flsFilePath', ...
            default = '', ...
            valFunc = IA.make_path_valfun('Loads.flsFilePath', 'extension', {'.scm', '.mkv'}, 'mustExist', true), ...
            repeat = true)

        validate.Field('Loads.flsScalingFactor', ...
            default = nan, ...
            min_ = 0.1, ...
            max_ = 3, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('Loads.flsScalingLevel', ...
            default = nan, ...
            classes = [IA.CLS_NUM, IA.CLS_CELL], ...
            attributes = {'nonempty'}, ...
            repeat = true)

        validate.Field('Loads.inclinationValue', ...
            default = nan, ...
            max_ = 10, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG, ...
            repeat = true)

        validate.Field('Loads.inclinationValueFls', ...
            default = nan, ...
            max_ = 10, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG, ...
            repeat = true)

        validate.Field('Loads.inclinationUnit', ...
            default = char(Unit.deg), ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            valFunc = IA.make_multiple_list_valfun('Loads.inclinationUnit', string([Unit.deg, Unit.mm_m])), ...
            repeat = true)

        validate.Field('Loads.S1FilePath', ...
            default = '', ...
            valFunc = IA.make_path_valfun('Loads.S1FilePath', 'extension', {'.mat'}, 'mustExist', true), ...
            repeat = true)

        validate.Field('Loads.S1ScalingFactor', ...
            default = [1 1], ...
            min_ = 0.1, ...
            max_ = 3, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('Loads.S1ScalingLevel', ...
            default = [-1e6 1e6], ...
            classes = [IA.CLS_NUM, IA.CLS_CELL], ...
            attributes = {'nonempty'}, ...
            repeat = true)

        validate.Field('Loads.tag', ...
            default = '', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            repeat = true)

        validate.Field('Loads.ulsFilePath', ...
            default = '', ...
            valFunc = IA.make_path_valfun('Loads.ulsFilePath', 'extension', {'.dat', '.mat', '.meat', '.txt'}, ...
               'mustExist', true), ...
            repeat = true)

        validate.Field('Loads.ulsScalingFactor', ...
            default = nan, ...
            min_ = 0.1, ...
            max_ = 3, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('Loads.ulsScalingLevel', ...
            default = nan, ...
            classes = [IA.CLS_NUM, IA.CLS_CELL], ...
            attributes = {'nonempty'}, ...
            repeat = true)

        validate.Field('Loads.ALIGN_AT', ...
            default = 'interface', ...
            valFunc = IA.make_list_valfun('Loads.ALIGN_AT', lower(string(enumeration('Milk.AlignLoadsType')))), ...
            repeat = true)

        validate.Field('MACRO_GEOMETRIC_SCF', ...
            default = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('maxFlangeThickn', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 100, ...
            max_ = 400, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('maxFlangeWidth', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 250, ...
            max_ = 750, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('maxNBolts', ...
            default = nan, ...
            min_ = 50, ...
            max_ = 400, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('MAX_FAILURE_MODE_D_FLS_UTILIZATION', ...
            default = 5 / 6, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('MAX_VISIBLE_THREAD_LENGTH_TENSION', ...
            default = '1.1D', ...
            expected = '1.1D', ...
            valFunc = {@(x, ~) UsainUtils.LengthExpression.validate_str(x)})

        validate.Field('MAX_VISIBLE_THREAD_LENGTH_TORQUE', ...
            default = '0.4D', ...
            expected = '0.4D', ...
            valFunc = {@(x, ~) UsainUtils.LengthExpression.validate_str(x)})

        validate.Field('MAX_WELD_BULGE_SIZE', ...
            default = 5, ...
            expected = 5, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('minFlangeThickn', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 100, ...
            max_ = 400, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('minFlangeWidth', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 250, ...
            max_ = 750, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('MIN_GRIPPED_THREAD_LENGTH', ...
            default = '4P', ...
            expected = '4P', ...
            valFunc = {@(x, ~) UsainUtils.LengthExpression.validate_str(x)})

        validate.Field('minNBolts', ...
            default = nan, ...
            min_ = 50, ...
            max_ = 400, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('MIN_NOSE_HEIGHT', ...
            default = 40, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('MIN_NUMBER_BOLTS_FRACTION', ...
            default = 0.9, ...
            expected = 0.9, ...
            classes = IA.CLS_NUM, ...
            attributes = [IA.ATTR_NUM_SCPOS, '<', 1])

        validate.Field('MIN_VISIBLE_THREAD_LENGTH', ...
            default = '3P', ...
            expected = '3P', ...
            valFunc = {@(x, ~) UsainUtils.LengthExpression.validate_str(x)})

        validate.Field('NUT_TYPE', ...
            default = '', ...
            valFunc = {@(x, ~) usain.fastener.BaseCatalogData.validate_input(x, 1, ...
               usain.fastener.NutData.NUT_TYPES, 'NUT_TYPE')})

        validate.Field('PLOT_STRESS_PATHS', ...
            default = false, ...
            valFunc = {IA.make_bool_valfun('PLOT_STRESS_PATHS')})

        validate.Field('PLOT_STRESS_TRANSFER_FUNCS', ...
            default = false, ...
            valFunc = {IA.make_bool_valfun('PLOT_STRESS_TRANSFER_FUNCS')})

        validate.Field('PSF_BOLT_RESISTANCE', ...
            default = 1.25, ...
            expected = 1.25, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('PSF_BOLT_RESISTANCE_JPN', ...
            default = nan, ...
            classes = IA.CLS_NUM, ...
            attributes = [IA.ATTR_NUM_VECPOS, 'numel', 3])

        validate.Field('PSF_BOLT_RESISTANCE_JPN_TAG', ...
            default = {}, ...
            classes = IA.CLS_CELL, ...
            attributes = [IA.ATTR_CELL, 'numel', 3], ...
            valFunc = IA.make_multiple_list_valfun('PSF_BOLT_RESISTANCE_JPN_TAG', Milk.ExtremeLoads.EVENT_TAGS_JPN))

        validate.Field('PSF_CMPCLASS2_FLS', ...
            default = 1.0, ...
            expected = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('PSF_CMPCLASS2_ULS', ...
            default = 1.0, ...
            expected = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('PSF_FAVORABLE_LOADS', ...
            default = 0.9, ...
            expected = 0.9, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('PSF_FLANGE_MATERIAL_FLS', ...
            default = 1.25, ...
            expected = 1.25, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('PSF_MATERIAL_ULS', ...
            default = 1.1, ...
            expected = 1.1, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('RADIUS_SHIFT_FLANGE', ...
            default = 0, ...
            expected = 0, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SC)

        validate.Field('RADIUS_SHIFT_SHELL', ...
            default = 0, ...
            expected = 0, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SC)

        validate.Field('REACTION_DISTANCE_METHOD', ...
            default = 'tobinaga', ...
            valfunc = IA.make_list_valfun('REACTION_DISTANCE_METHOD', ...
               UsainUtils.UltimateLimitState.VALID_REACTION_DIST_METHODS))

        validate.Field('RHO_FLANGE', ...
            default = 7850, ...
            expected = 7850, ...
            units = Unit.kg_m3, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('runName', ...
            default = '', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR)

        validate.Field('S1_BENDING_MOMENT', ...
            default = nan, ...
            units = Unit.kNm, ...
            min_ = 0, ...
            max_ = 1e6, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('SECONDARY_HOLES_BCD', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 2500, ...
            max_ = 7500, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SECONDARY_HOLES_DIAMETER', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 10, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SGRE2.BENDING_CONTRIBUTION', ...
            default = nan, ...
            min_ = 0.5, ...
            max_ = 1.0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SGRE2.FLANGE_TILT_UNIT', ...
            default = char(Unit.deg), ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            valFunc = IA.make_multiple_list_valfun('SGRE2.FLANGE_TILT_UNIT', string([Unit.deg, Unit.mm])))

        validate.Field('SGRE2.FLANGE_TILT_VALUE', ...
            default = 0, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('SGRE2.FLATNESS_TOLERANCE', ...
            default = 1.4, ...
            units = Unit.mm, ... % TODO should become mm_m, but likely needs to be included from master first...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SGRE2.GAP_ANGLE', ...
            default = [30, 60, 90, 120], ...
            units = Unit.deg, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('SGRE2.GAP_CLOSE_STIFFNESS_RATIO', ...
            default = 0.5, ...
            expected = 0.5, ...
            max_ = 1.0, ...
            min_ = 0.5, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SGRE2.INITIAL_POINT_OFFSET', ...
            default = 0.05, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SGRE2.INITIAL_SLOPE_REFERENCE_PRELOAD', ...
            default = 0.50, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('SGRE2.SHELL_STIFFNESS_METHOD', ...
            default = 'interpolated', ...
            valfunc = IA.make_list_valfun('SGRE2.SHELL_STIFFNESS_METHOD', ...
               usain.sgre2.ShellStiffness.VALID_SHELL_STIFFNESS_METHODS))

        validate.Field('SGRE2.WRITE_INTERMEDIATE_RESULTS', ...
            default = true, ...
            valFunc = {IA.make_bool_valfun('SGRE2.WRITE_INTERMEDIATE_RESULTS')})

        validate.Field('site', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR, ...
            valFunc = IA.make_enum_valfun('site', 'usain.inputs.Site'))

        validate.Field('SlsPretension.CUSTOM_PRELOAD', ...
            default = nan, ...
            units = Unit.kN, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS, ...
            repeat = true)

        validate.Field('SN_CURVE_NECK', ...
            default = 'EC3_DC90', ...
            classes = IA.CLS_CHAR, ...
            attributes = IA.ATTR_CHAR)

        validate.Field('STEPSIZE_BOLT_EXT_LEN', ...
            default = 1, ...
            expected = 1, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('STEPSIZE_NBOLTS', ...
            default = 4, ...
            min_ = 1, ...
            max_ = 4, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('STEPSIZE_THICKN', ...
            default = 1, ...
            expected = 1, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

         validate.Field('STEPSIZE_WIDTH', ...
            default = 1, ...
            units = Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('structureInpFilePath', ...
            default = '', ...
            valFunc = IA.make_path_valfun('structureInpFilePath', 'extension', {'.mat', '.xlsm'}, ...
               'mustExist', true))

        validate.Field('TEMP_STAGES_TOOL_TYPE', ...
            default = 'normal', ...
            valFun = {@(x, ~) usain.fastener.BaseCatalogData.validate_input(x, 1, ...
               usain.fastener.TighteningToolData.TEMP_STAGES_TOOL_TYPES, 'TEMP_STAGES_TOOL_TYPE')})

         validate.Field('targetDir', ...
            default = '', ... % This default value is overwritten in USAIN.m:do_post_parse_manipulations()
            valFunc = IA.make_path_valfun('targetDir', 'mustExist', false))

         validate.Field('thicknNoseLo', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 15, ...
            max_ = 150, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

         validate.Field('thicknNoseUp', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 15, ...
            max_ = 150, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCPOS)

        validate.Field('tighteningMethod', ...
            valFunc = IA.make_multiple_list_valfun('tighteningMethod', ...
            usain.fastener.TighteningToolData.VALID_TIGHTENING_METHOD))

        validate.Field('TIGHTENING_SIDE_INSTALLATION', ...
            default = 'upper', ...
            valFunc = IA.make_multiple_list_valfun('TIGHTENING_SIDE_INSTALLATION', {'upper', 'lower'}))

        validate.Field('TIGHTENING_SIDE_TEMP_STAGES', ...
            default = 'both', ...
            valFunc = IA.make_multiple_list_valfun('TIGHTENING_SIDE_TEMP_STAGES', {'upper', 'lower', 'both'}))

        validate.Field('TOL_BCD', ...
            default = 4, ...
            expected = 4, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_BCD_TOOL_WALL', ...
            default = 4, ...
            expected = 4, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_BOLT_HOLE', ...
            default = 0.5, ...
            expected = 0.5, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_EXTENDER_LENGTH', ...
            default = 0.5, ...
            expected = 0.5, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_FILLET_RADIUS_PLUS', ...
            default = 1, ...
            expected = 1, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_FLANGE_THICKNESS_MINUS', ...
            default = 2, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_FLANGE_THICKNESS_PLUS', ...
            default = 2, ...
            expected = 2, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOL_FLANGE_WIDTH', ...
            default = 2, ...
            expected = 2, ...
            units =  Unit.mm, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('TOOL_DIMENSION_CIRC_DIR', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 40, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('TOOL_DIMENSION_RADIAL_DIR', ...
            default = nan, ...
            units = Unit.mm, ...
            min_ = 40, ...
            max_ = 100, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_VECPOS)

        validate.Field('ULS_BENDING_MOMENT', ...
            default = nan, ...
            units = Unit.kNm, ...
            min_ = 0, ...
            max_ = 1e6, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SCNONNEG)

        validate.Field('zFlange', ...
            min_ = -200, ...
            max_ = 200, ...
            units = Unit.m, ...
            classes = IA.CLS_NUM, ...
            attributes = IA.ATTR_NUM_SC)

      ];

    Schema = validate.Schema(fields);
end
