function Steps = get_condition_steps(modelType)
    % Temporary helper method to create a list of `usain.conditions.BaseConditionStep` implementations

    assert(matches(modelType, ["flangemodel", "selectedmodel"]), 'Invalid input option.');
    doRunOnSelectedModel = modelType == "selectedmodel";

    % Generate list with all conditions, in order of execution
    Steps = { ...
        usain.conditions.ThreadRequirementsStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.BoltForceModelApplicabilityStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.FlangePlasticityStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.BoltPlasticityStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.UltimateLimitStateStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.UltimateLimitStateJapanStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.SlsPretensionLossStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.FlangeGappingStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.FatigueLimitStateStep(doRunOnSelectedModel = doRunOnSelectedModel), ...
        usain.conditions.FlangeNeckScfStep(doRunOnSelectedModel = doRunOnSelectedModel) ...
        };

end
