site_name: USAIN
site_description: User documentation for USAIN.

docs_dir: docs
site_dir: _build

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - First run: tutorials/first-run.md
    - Review results: tutorials/reviewing.md
    - TEXACO integration: tutorials/texaco.md
  - How-to guides:
    - How-to guides: howto/index.md
    - Update an input file for a new USAIN version: howto/update-inputfile.md
    - Multiple bolt FLS: howto/multiple-bolt-fls.md
  - Reference guides:
    - Reference guides: reference/index.md
    - User commands: reference/commands.md
    - Input file description: reference/inputfile.md
    - Expert inputs: reference/expert-inputs.md
    - Fastener properties: reference/fastener-props.md
    - Japanese design settings: reference/Japan-design.md
  - Explanation:
    - Explanation: explanation/index.md
    - FAQ: explanation/faq.md
    - The design space: explanation/design-space.md
    - Handling bounds: explanation/handling-bounds.md
    - Steps: explanation/steps.md
    - T-flanges: explanation/t-flanges.md
    - SCFs and load scaling: explanation/scfs-and-load-scaling.md
    - Developer documentation:
      - Developer documentation: explanation/developer-documentation/index.md
      - Flange tilt calculations: explanation/developer-documentation/flange-tilt-calculations.md
      - ULS failure modes: explanation/developer-documentation/uls-failure-modes.md
  - About:
    - About: about/index.md
    - Release notes: about/release-notes.md
    - Version notes: about/version-notes.md
