function varargout = run_all_usain_tests(namedArgs)
    arguments
        namedArgs.doRunCoverage (1, 1) logical = false
    end

    results = Unittest.run('*', ...
        {'unit', 'integration', 'system_integration', 'health_check'}, ...
        '*', ...
        'excludeTags', {}, ...
        'Directory', [pathlib.Path(which('USAIN')).parent.full_path, ...
            pathlib.Path('$ENGINEERING_CODEBASE_HOME/matlab/of/struct/Common/+design_space').expandvars().full_path, ...
            pathlib.Path('$ENGINEERING_CODEBASE_HOME/matlab/on/TOMATE/+tomate/+texaco_integration/+check_run').expandvars().full_path], ... % mh:ignore_style
        "RunCoverage", namedArgs.doRunCoverage);

    if nargout
        varargout{1} = results;
    end
end
