classdef (SharedTestFixtures = {Unittest.fixtures.SilentlyLogWarningsFixture}) ...
        FilePort_Test < Unittest.TestCase

    methods

        function UsainObj = create_fake_usain_object(Obj)
            % Returns a fake USAIN object that can be used for testing FilePort.create_export_layer()

            % We can use a struct for this; the actual USAIN instance is not needed
            UsainObj = struct();

            % Add data that is required for the logic in usain.io.FilePort.create_export_layer
            Inputs = Obj.applyFixture(usain.inputs.test.fixtures.ManipulatedInputsFixture(n = 1)).data;
            UsainObj.Mdl.Inputs = Inputs;

            UsainObj.Mdl.Loads = usain.loads.Loads();
            UsainObj.Mdl.Loads.Inputs = Inputs;

            UsainObj.Mdl.Condit.Fls.BoltForceModel.boltCurveXy = ones(4, 2) .* [1 2];
            UsainObj.Mdl.Condit.Fls.BoltForceModel.boltCurveMrks.fls = ones(1, 2) * 3;
            UsainObj.Mdl.Condit.Fls.BoltForceModel.boltCurveMrks.uls = ones(1, 2) * 4;

            % Add some more data to be able to test the add_field() commands
            UsainObj.Mdl.Tool.defaultPreload = 1000;
            UsainObj.Mdl.Wash.diamIn = 100;
            UsainObj.Mdl.Wash.diamOut = 200;
            UsainObj.Mdl.Wash.len = 123;
            UsainObj.Mdl.diameterOutNeck = Inputs.diameter;
            UsainObj.Mdl.diameterBoltCircle = Inputs.diamBoltCircle;
            UsainObj.Mdl.Segment.distForce = 0.123;
        end

    end

    methods (Test, TestTags = {'unit'})

        function hash__expected(Obj)
            % GIVEN not run as compiled code and the SHA1 hash
            Obj.assumeFalse(isdeployed(), 'Skip this test when run as compiled code');
            actualClassName = 'usain.io.FilePort';
            actual = io.hash_file(which(actualClassName));

            % WHEN, THEN
            expected = 'fcd344d858d9f4de3eec96b1daab6883ad070b12';
            Obj.verifyEqual(actual, expected, ...
                sprintf(['Hash of %s class file changed!\n', ...
                'This hints at the class code being changed.\n', ...
                'If the change is not relevant for Python, update the expected checksum.\n', ...
                'Otherwise, follow the guide in "guides/fileport-matlab.md".'], ...
                actualClassName));
        end

        function file_version__expect_version(Obj)
            % GIVEN, WHEN, THEN
            expected = '1.8.0';
            Obj.assertEqual(usain.io.FilePort().FILE_VERSION, expected, ...
                sprintf(['Expected the file version in usain.io.FilePort to be "%s". ', ...
                    'If the file version has changed, make sure to contact developers that maintain code that, ', ...
                    'depends on this (e.g. DOCTOR, SPARROW, Azure-DOCTOR)'], expected));
        end

        function tool_name__expect_name(Obj)
            % GIVEN, WHEN, THEN
            Obj.assertEqual(usain.io.FilePort().toolName, USAIN.TOOL_NAME);
        end

        function tool_version__expect_version(Obj)
            % GIVEN, WHEN, THEN
            Obj.assertEqual(usain.io.FilePort().toolVersion, USAIN.VERSION);
        end

        function save_file__overwrite_existing_files(Obj)
            % GIVEN a nonexisting file
            p = pathlib.Path(mfilename('fullpath')).parent / '_generated' / 'fileport-test01.usn';
            if p.is_file()
                delete(char(p));
            end

            % WHEN, THEN
            F = usain.io.FilePort();
            F.save_file(p);
            Obj.assertTrue(p.is_file());

            % WHEN saving the same file again, THEN
            Obj.assertError(@() F.save_file(p), 'FilePort:ExistingPath');

            % WHEN saving the same file again, but with the 'force' arg, THEN
            Obj.verify_error_free(@() F.save_file(p, true));
        end

        function save_file__folder_input(Obj)
            % GIVEN, WHEN, THEN
            F = usain.io.FilePort();
            Obj.assertError(@() F.save_file(pwd), 'FilePort:FilePath');
        end

        function get_object_to_save__converted_to_basic_types(Obj)
            % GIVEN
            F = usain.io.FilePort();

            % WHEN filling the FilePort with dummy data
            O = gobjects();
            O.addprop('a');
            O.a = 'a';
            F.data.a = O;  % to test if objects are converted to structs
            F.data.b.c = 123;

            % THEN
            Actual = F.get_object_to_save();

            Obj.assertClass(Actual, 'struct');
            Obj.assertTrue(isfield(Actual, 'FILE_VERSION'));
            Obj.assertTrue(isfield(Actual, 'toolName'));
            Obj.assertTrue(isfield(Actual, 'toolVersion'));
            Obj.assertTrue(isfield(Actual, 'data'));
            Obj.assertTrue(isfield(Actual, 'TYPES'));
            Obj.assertTrue(isstruct(Actual.data.a));  % converted to struct
            Obj.assertEqual(Actual.data.b.c, 123);
        end

        function get_data__expected_fields(Obj)
            % GIVEN a fake USAIN instance with some pre-defined data
            UsainObj = Obj.create_fake_usain_object();

            % WHEN we construct the FilePort
            actual = usain.io.FilePort.get_data(UsainObj);

            % THEN
            Obj.assertClass(actual, 'struct');
            Obj.assertEqual(actual.washer.diameterIn, 100);
            Obj.assertEqual(actual.washer.diameterOut, 200);
            Obj.assertEqual(actual.washer.thickness, 123);
            Obj.assertEqual(actual.boltForceModel.plotData.line.x, [1, 1, 1, 1]');
            Obj.assertEqual(actual.boltForceModel.plotData.marker.y, [3, 4]);

            % WHEN we do the same, but then through the constructor of usain.io.FilePort
            F = usain.io.FilePort(UsainObj);

            % THEN we expect a FilePort object to be returned, with the exact same data as before
            Obj.assertClass(F, 'usain.io.FilePort');
            Obj.assertEqual(F.data.washer.diameterIn, 100);
            Obj.assertEqual(F.data.washer.diameterOut, 200);
            Obj.assertEqual(F.data.washer.thickness, 123);
            Obj.assertEqual(F.data.boltForceModel.plotData.line.x, [1, 1, 1, 1]');
            Obj.assertEqual(F.data.boltForceModel.plotData.marker.y, [3, 4]);
        end

        function get_data__types_described(Obj)
            % GIVEN a fake USAIN instance with some pre-defined data
            UsainObj = Obj.create_fake_usain_object();

            % WHEN we construct the FilePort object with the fake USAIN data
            F = usain.io.FilePort(UsainObj);

            % THEN we expect a type description for each field in data
            for field = fieldnamesr(F.data)'
                Obj.assertTrue(issubfield(F.TYPES, field{1}), sprintf('Error for field: %s', field{1}));
            end
        end

        function get_types__all_expected_fields(Obj)
            % GIVEN, WHEN
            types = usain.io.FilePort.get_types();

            % THEN we expect exactly the following fields
            expected = [
                "bolt.boltOptionLabel", ...
                "bolt.diameter", ...
                "bolt.eModulus", ...
                "bolt.length", ...
                "bolt.threadLength", ...
                "bolt.propertyClass", ...
                "bolt.ultimateStrength", ...
                "conditions.boltForceModelApplicability.utilRatio", ...
                "conditions.boltForceModelApplicability.isAssessed", ...
                "conditions.fls.additionalScf", ...
                "conditions.fls.macroGeometricScf", ...
                "conditions.fls.pmSum", ...
                "conditions.fls.pmSumInverse", ...
                "conditions.fls.pmSumNorm", ...
                "conditions.fls.pmSumNormInverse", ...
                "conditions.fls.sizeEffect", ...
                "conditions.fls.snCurveLabel", ...
                "conditions.fls.utilRatio", ...
                "conditions.fls.utilRatioGeometry", ...
                "conditions.fls.boltForceModelName", ...
                "conditions.fls.targetPmSum", ...
                "conditions.fls.isAssessed", ...
                "conditions.thread.grippedThreadLengthLowerFlange", ...
                "conditions.thread.grippedThreadLengthUpperFlange", ...
                "conditions.thread.visibleThreadLengthLowerFlange", ...
                "conditions.thread.visibleThreadLengthUpperFlange", ...
                "conditions.thread.isAssessed", ...
                "conditions.uls.failureModeA", ...
                "conditions.uls.failureModeB", ...
                "conditions.uls.failureModeD", ...
                "conditions.uls.failureModeCritical", ...
                "conditions.uls.failureModeE", ...
                "conditions.uls.forceDesign", ...
                "conditions.uls.isAssessed", ...
                "conditions.uls.utilRatio", ...
                "conditions.uls.yieldStrengthDesign", ...
                "conditions.ulsJapan.failureModeA", ...
                "conditions.ulsJapan.failureModeB", ...
                "conditions.ulsJapan.failureModeC", ...
                "conditions.ulsJapan.failureModeCritical", ...
                "conditions.ulsJapan.forceDesign", ...
                "conditions.ulsJapan.isAssessed", ...
                "conditions.ulsJapan.utilRatio", ...
                "conditions.ulsJapan.yieldStrengthDesign", ...
                "designspace.numberOfBoltsMin", ...
                "designspace.numberOfBoltsMax", ...
                "designspace.thicknessFlangeMin", ...
                "designspace.thicknessFlangeMax", ...
                "designspace.widthFlangeMin", ...
                "designspace.widthFlangeMax", ...
                "extender.diameterIn", ...
                "extender.diameterOut", ...
                "extender.length", ...
                "flange.bevelAngle", ...
                "flange.bevelRootFace", ...
                "flange.boltCircleDiameter", ...
                "flange.boltCircleDiameterMin", ...
                "flange.boltCircleDiameterMax", ...
                "flange.boltHoleDiameter", ...
                "flange.boltDistance", ...
                "flange.clearanceExtenderToFillet", ...
                "flange.clearanceToolToWeld", ...
                "flange.clearanceWasherToLowerFillet", ...
                "flange.clearanceWasherToUpperFillet", ...
                "flange.clearanceWeldToLowerFillet", ...
                "flange.clearanceWeldToUpperFillet", ...
                "flange.density", ...
                "flange.eModulus", ...
                "flange.filletRadius", ...
                "flange.lowerFlangeThicknessAllowance", ...
                "flange.upperFlangeThicknessAllowance", ...
                "flange.flangeType", ...
                "flange.materialDesignation", ...
                "flange.massBoltAssembly", ...
                "flange.massFlangeLower", ...
                "flange.massFlangeUpper", ...
                "flange.massStubLower", ...
                "flange.massStubUpper", ...
                "flange.minNoseHeight", ...
                "flange.minNoseHeightLower", ...
                "flange.minNoseHeightUpper", ...
                "flange.neckHeightLower", ...
                "flange.neckHeightUpper", ...
                "flange.neckThicknessLower", ...
                "flange.neckThicknessUpper", ...
                "flange.outerBoltCircleDiameter", ...
                "flange.outerNeckDiameter", ...
                "flange.outerStubDiameter", ...
                "flange.segment.loadFactor", ...
                "flange.segment.parameterA", ...
                "flange.segment.parameterB", ...
                "flange.segment.resilienceBolt", ...
                "flange.segment.resilienceClampedParts", ...
                "flange.segment.resilienceFlanges", ...
                "flange.space.nBolts", ...
                "flange.space.thickness", ...
                "flange.space.width", ...
                "flange.totalHeightLower", ...
                "flange.totalHeightUpper", ...
                "flange.yieldStrengthCharacteristic", ...
                "flange.zCoordinate", ...
                "general.countryCode", ...
                "general.delReferenceCycles", ...
                "general.delWohlerSlope", ...
                "general.doAssessFls", ...
                "general.site", ...
                "general.structuralModelInputPath", ...
                "general.structuralModelOutputPath", ...
                "loads.deadWeightFavorDesign", ...
                "loads.delDesign", ...
                "loads.flsLoadsPath", ...
                "loads.inclinationValue", ...
                "loads.inclinationUnit", ...
                "loads.inclinationMomentDesign", ...
                "loads.markovFolder", ...
                "loads.maxFlsMoment", ...
                "loads.nLoadSets", ...
                "loads.tag", ...
                "loads.ulsLoadsPath", ...
                "loads.ulsMomentDesign", ...
                "loads.ulsMomentDlc", ...
                "nut.height", ...
                "nut.label", ...
                "partialSafetyFactor.boltMaterialFls", ...
                "partialSafetyFactor.boltResistance", ...
                "partialSafetyFactor.componentClassFls", ...
                "partialSafetyFactor.componentClassUls", ...
                "partialSafetyFactor.favorableLoads", ...
                "partialSafetyFactor.materialUls", ...
                "tolerance.boltCircleDiameter", ...
                "tolerance.boltHole", ...
                "tolerance.extenderLength", ...
                "tolerance.filletRadiusPlus", ...
                "tolerance.flangeThicknessMinus", ...
                "tolerance.flangeThicknessPlus", ...
                "tolerance.flangeWidth", ...
                "tool.assemblyValue", ...
                "tool.preloadFls", ...
                "tool.preload", ...
                "tool.tighteningMethod", ...
                "tool.tighteningSideInstallation", ...
                "washer.customWasherDiameterIn", ...
                "washer.customWasherDiameterOut", ...
                "washer.customWasherThickness", ...
                "washer.diameterIn", ...
                "washer.diameterOut", ...
                "washer.thickness", ...
                "boltForceModel.SELF", ...
                "boltForceModel.petersen.SELF", ...
                "boltForceModel.petersen.zCr", ...
                "boltForceModel.preloadLossFactor", ...
                "boltForceModel.plotData.line.x", ...
                "boltForceModel.plotData.line.y", ...
                "boltForceModel.plotData.marker.legendEntries", ...
                "boltForceModel.plotData.marker.x", ...
                "boltForceModel.plotData.marker.y", ...
                "boltForceModel.schmidtNeuper.SELF", ...
                "boltForceModel.schmidtNeuper.z1", ...
                "boltForceModel.schmidtNeuper.z2", ...
                "boltForceModelSecond.SELF", ...
                "boltForceModelSecond.petersen.SELF", ...
                "boltForceModelSecond.petersen.zCr", ...
                "boltForceModelSecond.preloadLossFactor", ...
                "boltForceModelSecond.boltMaterialFls", ...
                "boltForceModelSecond.schmidtNeuper.SELF", ...
                "boltForceModelSecond.schmidtNeuper.z1", ...
                "boltForceModelSecond.schmidtNeuper.z2" ...
                ];
            actual = string(fieldnamesr(types));
            notInExpected = setdiff(actual, expected);
            notInActual = setdiff(expected, actual);
            Obj.assertEmpty(notInExpected, 'These fields are not in the expected list');
            Obj.assertEmpty(notInActual, 'These fields are not in the actual list');
        end

    end

end
