classdef RunOutputData_Test < Unittest.TestCase

    methods (Test, TestTags = {'unit'})

        function constructor__happy_without_optionals(Obj)
            % GIVEN
            % WHEN
            Actual = usain.io.RunOutputData( ...
                didAdjustStrMdl = false, ...
                logFilePath = 'foo', ...
                selectedModelInputFilePath = 'bar', ...
                usnFilePath = 'bla');

            % THEN
            Obj.verifyClass(Actual, 'usain.io.RunOutputData');

            Obj.verifyEqual(Actual.didAdjustStrMdl, false);
            Obj.verifyEqual(Actual.logFilePath, "foo");
            Obj.verifyEqual(Actual.selectedModelInputFilePath, "bar");
            Obj.verifyEqual(Actual.strucModFilePath, "");
            Obj.verifyEqual(Actual.usnFilePath, "bla");

            Obj.verifyEmpty(Actual.FlangeNeckScf);
        end

        function constructor__happy_with_optionals(Obj)
            % GIVEN
            EqvScf = usain.io.EquivalentScfData( ...
                labels = ["FL02", "FL03"], ...
                bendingScfInside = [1.1 1.2], ...
                bendingScfOutside = [1.3 1.4]);

            % WHEN
            Actual = usain.io.RunOutputData( ...
                didAdjustStrMdl = false, ...
                logFilePath = 'foo', ...
                selectedModelInputFilePath = 'bar', ...
                strucModFilePath = 'baz', ...
                usnFilePath = 'bla', ...
                FlangeNeckScf = EqvScf);

            % THEN
            Obj.verifyClass(Actual, 'usain.io.RunOutputData');

            Obj.verifyEqual(Actual.didAdjustStrMdl, false);
            Obj.verifyEqual(Actual.logFilePath, "foo");
            Obj.verifyEqual(Actual.selectedModelInputFilePath, "bar");
            Obj.verifyEqual(Actual.strucModFilePath, "baz");
            Obj.verifyEqual(Actual.usnFilePath, "bla");

            Obj.verifyClass(Actual.FlangeNeckScf, 'usain.io.EquivalentScfData');
        end

        function constructor__happy_without_optionals_in_struct(Obj)
            % GIVEN
            S = struct( ...
                didAdjustStrMdl = false, ...
                logFilePath = 'foo', ...
                selectedModelInputFilePath = 'bar', ...
                usnFilePath = 'bla');

            % WHEN
            Actual = usain.io.RunOutputData(S);

            % THEN
            Obj.verifyClass(Actual, 'usain.io.RunOutputData');

            Obj.verifyEqual(Actual.didAdjustStrMdl, false);
            Obj.verifyEqual(Actual.logFilePath, "foo");
            Obj.verifyEqual(Actual.selectedModelInputFilePath, "bar");
            Obj.verifyEqual(Actual.strucModFilePath, "");
            Obj.verifyEqual(Actual.usnFilePath, "bla");

            Obj.verifyEmpty(Actual.FlangeNeckScf);
        end

        function constructor__happy_with_optionals_in_struct(Obj)
            % GIVEN
            EqvScfStruct = struct( ...
                labels = ["FL02", "FL03"], ...
                bendingScfInside = [1.1 1.2], ...
                bendingScfOutside = [1.3 1.4]);

            S = struct( ...
                didAdjustStrMdl = false, ...
                logFilePath = 'foo', ...
                selectedModelInputFilePath = 'bar', ...
                strucModFilePath = 'baz', ...
                usnFilePath = 'bla', ...
                FlangeNeckScf = EqvScfStruct);

            % WHEN
            Actual = usain.io.RunOutputData(S);

            % THEN
            Obj.verifyClass(Actual, 'usain.io.RunOutputData');

            Obj.verifyEqual(Actual.didAdjustStrMdl, false);
            Obj.verifyEqual(Actual.logFilePath, "foo");
            Obj.verifyEqual(Actual.selectedModelInputFilePath, "bar");
            Obj.verifyEqual(Actual.strucModFilePath, "baz");
            Obj.verifyEqual(Actual.usnFilePath, "bla");

            Obj.verifyClass(Actual.FlangeNeckScf, 'usain.io.EquivalentScfData');
        end

        function constructor__flangeneckscf_empty(Obj)
            % GIVEN, WHEN, THEN
            Actual = usain.io.RunOutputData( ...
                didAdjustStrMdl = false, ...
                logFilePath = 'foo', ...
                selectedModelInputFilePath = 'bar', ...
                usnFilePath = 'bla', ...
                FlangeNeckScf = usain.io.EquivalentScfData.empty);
            Obj.verifyClass(Actual, 'usain.io.RunOutputData');
        end

        function constructor__flangeneckscf_scalar(Obj)
            % GIVEN
            EqvScf = usain.io.EquivalentScfData( ...
                labels = ["FL02", "FL03"], ...
                bendingScfInside = [1.1 1.2], ...
                bendingScfOutside = [1.3 1.4]);

            % WHEN, THEN
            Actual = usain.io.RunOutputData( ...
                didAdjustStrMdl = false, ...
                logFilePath = 'foo', ...
                selectedModelInputFilePath = 'bar', ...
                usnFilePath = 'bla', ...
                FlangeNeckScf = EqvScf);
            Obj.verifyClass(Actual, 'usain.io.RunOutputData');
        end

        function constructor__flangeneckscf_array(Obj)
            % GIVEN
            EqvScf(1) = usain.io.EquivalentScfData( ...
                labels = ["FL02", "FL03"], ...
                bendingScfInside = [1.1 1.2], ...
                bendingScfOutside = [1.3 1.4]);
            EqvScf(2) = EqvScf(1);

            % WHEN, THEN
            Obj.assertRaisesMessageRegex( ...
                @() usain.io.RunOutputData( ...
                    didAdjustStrMdl = false, ...
                    logFilePath = 'foo', ...
                    selectedModelInputFilePath = 'bar', ...
                    usnFilePath = 'bla', ...
                    FlangeNeckScf = EqvScf), ...
                'Value must be scalar or empty.');
        end

    end
end
